import { GoogleGenAI } from '@google/genai';

export const enhancePromptWithGemini = async (apiKey: string, basePrompt: string) => {
  const ai = new GoogleGenAI({ apiKey });
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Enhance the following basic prompt for an image generator. Add descriptive details, lighting, atmosphere, and high-quality keywords. Make it a single, cohesive paragraph. Do not include any meta-commentary like "Here is your prompt". Just return the enhanced prompt.
    Base prompt: "${basePrompt}"`
  });
  return response.text?.trim() || basePrompt;
};

export const generateImageWithGemini = async (apiKey: string, prompt: string, aspectRatio: "1:1" | "16:9" | "9:16" | "4:3" = "1:1", negativePrompt?: string) => {
  const ai = new GoogleGenAI({ apiKey });
  
  // Incorporate negative prompt if provided
  const fullContents: string = negativePrompt 
    ? `${prompt}\n\n[Avoid: ${negativePrompt}]` 
    : prompt;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: {
      parts: [{ text: fullContents }]
    },
    config: {
      imageConfig: {
        aspectRatio: aspectRatio
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      // Create data URL
      const base64EncodeString: string = part.inlineData.data;
      return `data:${part.inlineData.mimeType || 'image/jpeg'};base64,${base64EncodeString}`;
    }
  }

  throw new Error("No image generated by the AI.");
};
